name: Unity Build & Deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          email: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}
          serial: ''   # dla licencji Personal zostaw puste
          targetPlatform: WebGL
          unityVersion: 6000.0.50f1   # sprawdź w ProjectVersion.txt
        env:
          UNITY_VERSION: 6000.0.50f1
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

  deploy:
    name: Deploy to itch.io
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Build
          path: build

      - name: Zip WebGL build
        run: |
          cd build/WebGL
          zip -r ../../WebGLBuild.zip .

      - name: Install butler
        run: |
          curl -L https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default | tar -xvz
          sudo mv butler /usr/local/bin/butler

      - name: Upload to itch.io
        run: |
          butler push WebGLBuild.zip isormour/game:html5
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}